services: 
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    
  api:
    build: ./api
    image: rhibro/api:v1.0.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

  cache:
    image: redis:latest
    ports:
      - "6379:6379"

  tester: 
    image: alpine
    command: ["sleep", "infinity"] # keeps it running 
    depends_on:
     - db
     - api
     - cache 

volumes:
  db-data: