name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      # - name: Set up Azure CLI
      #   uses: azure/setup-cli@v1 

      - name: Log in to Azure
        run: |
          echo "${{ secrets.AZURE_PASSWORD }}" | az login --service-principal -u "${{ secrets.AZURE_APP_ID }}" -p --tenant "${{ secrets.AZURE_TENANT }}"

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_URL }}/docker-compose-intro-build:latest .
          # Replace 'my-image' with your desired image name

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_URL }}/my-image:latest
