name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out the code
        uses: actions/checkout@v2

      # Log in to Azure using service principal
      - name: Log in to Azure
        run: |
          echo "" | az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_USERNAME }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_URL }}/docker-compose-intro-build:latest .

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_URL }}/docker-compose-intro-build:latest



    ## now it's docker again docker docker