name: Init Database

on:
  workflow_dispatch:

jobs:
  init-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run init.sql against Azure DB
        env:
          PGPASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          PGHOST: ${{ secrets.AZURE_DB_HOST }}
          PGPORT: ${{ secrets.AZURE_DB_PORT }}
          PGUSER: ${{ secrets.AZURE_DB_USER }}
          PGDATABASE: ${{ secrets.AZURE_DB_NAME }}
        run: |
          echo "Running init.sql against $PGHOST/$PGDATABASE as $PGUSER"
          # ensure path to your init.sql is correct
          psql "host=$PGHOST port=$PGPORT dbname=$PGDATABASE user=$PGUSER sslmode=require" -f ./db/init.sql
